package DTO;

import java.io.Serializable;

/**
* 注文詳細 モデルクラス.
*
* @author generated by ERMaster
* @version $Id$
*/
public class OrderDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 詳細ID. */
	private Integer detailId;

	/** 商品. */
	private String productid;

	/**注文ID. */
	private Integer ordersid;

	/** 注文数. */
	private Integer quentity;

	/** 備考. */
	private String note;

	/**
	 * コンストラクタ.
	 */
	public OrderDetail() {
	}

	public Integer getQuentity() {
		return quentity;
	}

	public void setQuentity(Integer quentity) {
		this.quentity = quentity;
	}

	/**
	 * 詳細ID を設定します.
	 *
	 * @param detailId
	 *            詳細ID
	 */
	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	/**
	 * 詳細ID を取得します.
	 *
	 * @return 詳細ID
	 */
	public Integer getDetailId() {
		return this.detailId;
	}

	/**
	 * 商品 を設定します.
	 *
	 * @param product
	 *            商品
	 */
	public void setProductid(String productid) {
		this.productid = productid;
	}

	/**
	 * 商品 を取得します.
	 *
	 * @return 商品
	 */
	public String getProduct() {
		return this.productid;
	}

	/**
	 * 備考 を設定します.
	 *
	 * @param note
	 *            備考
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * 備考 を取得します.
	 *
	 * @return 備考
	 */
	public String getNote() {
		return this.note;
	}
	

	//注文IDを設定します
	public void setOrdersid(Integer ordersid) {
		this.ordersid = ordersid;
	}

	//注文IDを取得します
	public Integer getOrdersid() {
		return ordersid;
	}

	/**
	 * 明細行の合計金額を取得する。
	 * @return 明細行の合計金額
	 */
	//public Integer getTotal() {
	//	return productid.getUnitPrice() * this.quentity;
	//}
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((detailId == null) ? 0 : detailId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		OrderDetail other = (OrderDetail) obj;
		if (detailId == null) {
			if (other.detailId != null) {
				return false;
			}
		} else if (!detailId.equals(other.detailId)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return String.format("OrderDetail [detailId=%s, product=%s, quentity=%s, note=%s]", detailId,
				productid, quentity, note);
	}

}