package DTO;

import java.io.Serializable;

/**
 * 商品 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Product implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 商品ID. */
	private String id;

	/** 商品名. */
	private String name;

	/** 価格. */
	private Integer unitPrice;

	/** 量. */
	private Integer unitAmount;

	/** 備考. */
	private String note;

	/**
	 * コンストラクタ.
	 */
	public Product() {
		super();
	}

	
	/**
	 * @param id
	 * @param name
	 * @param unitPrice
	 * @param unitAmount
	 */
	public Product(String id, String name, Integer unitPrice, Integer unitAmount) {
		super();
		this.id = id;
		this.name = name;
		this.unitPrice = unitPrice;
		this.unitAmount = unitAmount;
	}


	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getUnitPrice() {
		return unitPrice;
	}

	public void setUnitPrice(Integer unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Integer getUnitAmount() {
		return unitAmount;
	}

	public void setUnitAmount(Integer unitAmount) {
		this.unitAmount = unitAmount;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Product other = (Product) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return String.format("Product [id=%s, name=%s, unitPrice=%s, unitAmount=%s, note=%s]", id,
				name, unitPrice, unitAmount, note);
	}

}
