package DTO;

import java.io.Serializable;

/**
 * スタッフ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Staff implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** スタッフID. */
	private String id;

	/** スタッフ名. */
	private String name;

	/** 説明. */
	private String description;

	/** 権限レベル. */
	private Integer authorityLevel;

	/** 備考. */
	private String note;

	/**
	 * コンストラクタ.
	 */
	public Staff() {
		super();
	}

	/**
	 * コンストラクタ.
	 * @param name 
	 */
	public Staff(String name) {
		this.name = name;
	}

	/**
	 * スタッフID を設定します.
	 * 
	 * @param id
	 *            スタッフID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * スタッフID を取得します.
	 * 
	 * @return スタッフID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * スタッフ名 を設定します.
	 * 
	 * @param name
	 *            スタッフ名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * スタッフ名 を取得します.
	 * 
	 * @return スタッフ名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 説明 を設定します.
	 * 
	 * @param description
	 *            説明
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * 説明 を取得します.
	 * 
	 * @return 説明
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * 権限レベル を設定します.
	 * 
	 * @param authorityLevel
	 *            権限レベル
	 */
	public void setAuthorityLevel(Integer authorityLevel) {
		this.authorityLevel = authorityLevel;
	}

	/**
	 * 権限レベル を取得します.
	 * 
	 * @return 権限レベル
	 */
	public Integer getAuthorityLevel() {
		return this.authorityLevel;
	}

	/**
	 * 備考 を設定します.
	 * 
	 * @param note
	 *            備考
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * 備考 を取得します.
	 * 
	 * @return 備考
	 */
	public String getNote() {
		return this.note;
	}

	@Override
	public String toString() {
		return String.format("Staff [id=%s, name=%s, description=%s, authorityLevel=%s, note=%s]", id,
				name, description, authorityLevel, note);
	}



}
